### PR TITLE
Fix url in cot.rb

### LINKED ISSUE #1: Formula's url should be tag's one, not master's one
https://github.com/coteditor/homebrew-coteditor/blob/1b9ddb948798e714a821bf8e924f67275f4f2c31/cot.rb#L4-L5

When https://raw.githubusercontent.com/coteditor/cot/master/cot is updated, `brew install cot` will fail with `ChecksumMismatchError: SHA256 mismatch` error. So `url "https://raw.githubusercontent.com/coteditor/cot/master/cot"` should be `url "https://raw.githubusercontent.com/coteditor/cot/2.6.2/cot"` to match with its pinned version.

### PR DESCRIPTION
**Pull request by ikesyo**
Should fix https://github.com/coteditor/homebrew-coteditor/issues/1.

- Specify a pinned version for `url`
- Remove `version` and let Homebrew infer the version
- Add `haed` to install a version on `master` (we can use `--HEAD` option now)

### CODE REVIEW

File: cot.rb [hunk 1]
```diff
@@ -1,8 +1,7 @@
 class Cot < Formula
   desc "The command-line helper tool for CotEditor"
   homepage "https://coteditor.com/"
-  url "https://raw.githubusercontent.com/coteditor/cot/master/cot"
-  version "2.6.2"
```
Comment (ikesyo) [inline cot.rb:5]: https://www.rubydoc.info/github/Homebrew/brew/master/Formula#version-class_method

> The version is autodetected from the URL and/or tag so only needs to be declared if it cannot be autodetected correctly.

File: cot.rb [hunk 2]
```diff
@@ -1,8 +1,8 @@
...
+  head "https://raw.githubusercontent.com/coteditor/cot/master/cot"
```
Comment (ikesyo) [inline cot.rb:4]: https://www.rubydoc.info/github/Homebrew/brew/master/Formula#head-class_method

**Comment by ikesyo** [comment]
@1024jp Could you take a look?

**Comment by 1024jp** [comment]
Thank you @ikesyo.
Sorry for my late. Last few weeks, I was just too busy to look into issues.

**Comment by ikesyo** [comment]
No problem, thanks for merging! 😄
